import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import BlogCard from '../components/BlogCard.js'
import { GraphQLClient, gql } from 'graphql-request';

const graphcms = new GraphQLClient(
  "https://api-eu-central-1-shared-euc1-02.hygraph.com/v2/clbw1lbp74bnd01t964894g85/master"
);

const QUERY = gql`
{
  posts {
    id
    title
    datePublished
    slug
    content {
    	html
  	}
    author {
      name
      avatar {
        url
      }
 		}
     coverPhoto{
  		url
  	}
  }
}
`;

export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate: 10,
  }
}

const inter = Inter({ subsets: ['latin'] })

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {posts.map((post) => (
          <BlogCard key={post.id}
            title={post.title}
            author={post.author}
            datePublished={post.datePublished}
            content={post.content}
            slug={post.slug}
            coverPhoto={post.coverPhoto}
          />
        ))}

      </main>
    </>
  )
}
